### ISSUE TITLE
Creating a jar fails

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/org.lappsgrid.discriminator.dsl#10]
Creating a jar with `make jar` or `mvn package` fails. This happens in the develop branch and not in the master branch so something iffy was probably introduced in commit 61ad637.

Here is the error message:

```
$ make jar
mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.lappsgrid.discriminator:dsl:1.2.0-SNAPSHOT: Could not find artifact org.lappsgrid.maven:groovy-parent-pom:pom:1.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.lappsgrid.discriminator:dsl:1.2.0-SNAPSHOT (/Users/marc/Desktop/lapps/code/lappsgrid-incubator/discriminator-dsl/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.lappsgrid.discriminator:dsl:1.2.0-SNAPSHOT: Could not find artifact org.lappsgrid.maven:groovy-parent-pom:pom:1.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
make: *** [jar] Error 1
```

**Comment by marcverhagen** [comment]
This was an issue with my Maven installation not knowing where to get the snapshots. There is a settings file at https://downloads.lappsgrid.org/scripts/settings.xml that should be added to your `~/.m2` directory.

This should perhaps be added to the repository's documentation (although it is probably relevant for a lot of repositories).

**Comment by ksuderman** [comment]
We should document this on the wiki under "Developer Notes" (or some such thing) as this is only relevant for people building development (SNAPSHOT) versions of the Java libraries.  End users will typically use the artifacts from Maven Central.

**Comment by marcverhagen** [comment]
Added a blurp on http://wiki.lappsgrid.org/technical/vocabulary.html  (not there yet since this is still in the develop branch, see https://github.com/lapps/lapps.github.io/commit/0f489e06 and https://github.com/lapps/lapps.github.io/commit/8a973a10).
