### ISSUE TITLE
Adding tagsets

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/org.lappsgrid.discriminator.dsl#6]
We do not have discriminators for tagsets yet. Two ways to do this (both by editing 
[discriminators.config](https://github.com/lappsgrid-incubator/org.lappsgrid.discriminator.dsl/blob/master/src/main/resources/discriminators.config)).

One way is to keep it in house and add a postagset URI to the discriminators:

```groovy
def meta = { "http://vocab.lappsgrid.org/ns/media/meta/$it" }

postagset {
   uri meta('postagset')
   description "POS tagset used." }

brown_tagset { 
   uri meta('tagset#brown')
   description "The Brown tag set, see <SOME_URL>" }
```

This probably requires resolution of issue https://github.com/lapps/vocabulary-pages/issues/39.

The other way is to make the URI for the discriminator the external link:

```groovy
def dkpro = { "https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/tagset-reference.html#$it" }

ptb_tagset {
   uri dkpro('tagset-en-ptb-pos')
   description 'Tag set used in the Penn Tree Bank'
}
```

**Comment by ksuderman** [comment]
I think I prefer the first method as it is consistent with what we have so far.  However, the base URI for tag sets should be something like http://vocab.lappsgrid.org/ns/tagsets as http://vocab.lappsgrid.org/ns/media is intended for media types.

```groovy
def tagset = { "http://vocab.lappsgrid.org/ns/tagset/$it" }

'pos-tagset' {
	uri tagset('pos')
	description "Part-Of-Speech tag set used."
}
'brown-tagset' {
	uri tagset('pos#brown')
	description "See <some uri>"
}
'dkpro-tagset-en-ptb-pos' {
	uri tagset('pos#dkpro-en-ptb')
	description 'See https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/tagset-reference.html#tagset-en-ptb-pos'
}
```
The other tag set types would use http://vocab.lappsgrid.org/ns/tagset/ner etc.

**Comment by ksuderman** [comment]
This issue was moved to lapps/vocabulary-pages#55 since that is where the actual work (i.e. editing the lapps.discriminator file) will take place.
