### ISSUE TITLE
Makefile issues

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/org.lappsgrid.discriminator.dsl#8]
There are several minor issues with the Makefile (vocabulary branch):

- [ ] In line 4 it defines `JAR=discriminator-dsl-$(VERSION).jar` whereas `mv package` generates `discriminator-$(VERSION).jar`
- [ ] In line 16 it defines `SCRIPT=$(HOME)/bin/d`, which probably should be `SCRIPT=$(HOME)/bin/ddsl`

These are easy to fix. But here is a meta question. If org.lappsgrid.discriminator.dsl now has the same function as vocabulary-dsl, then we should be able to massively simplify this makefile, right? And perhaps set it up in way very similar to [vocabulary-dsl/Makefile](https://github.com/lappsgrid-incubator/vocabulary-dsl/blob/develop/Makefile) with goals jar, install, release and upload.

**Comment by marcverhagen** [comment]
@ksuderman: I volunteer to clean this up, but only if you agree with me that most goals in the Makefile are useless now.

**Comment by ksuderman** [comment]
Let me check and make sure my latest changes have been pushed to GitHub.  There is a good chances I've already simplified this Makefile.

**Comment by ksuderman** [comment]
I've been making these changes in the *vocabulary* branch, and the Makefile there has been greatly simplified.
