### ISSUE TITLE
Description links

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/org.lappsgrid.discriminator.dsl#9]
URLs included in a discriminator's description should be rendered as links (anchors) in the generated HTML.

**Comment by marcverhagen** [comment]
Related to this, if there is html markup in the description then it should not be escaped. For example,  if we have `<b>` in the description then it will be printed as `&lt;b&gt;` and we get to enjoy the tag and not the rendering in the html.

**Comment by marcverhagen** [comment]
I was about to volunteer to do this but then I noticed that the code that does this is full of Groovy and template magic that would take me weeks to understand, so perhaps not.

**Comment by ksuderman** [comment]
I think the only two lines that need to be changed are:

1. [discriminator-index.template:96](https://github.com/lapps/vocabulary-pages/blob/master/templates/discriminator-index.template#L96)
1. [discriminator-page.template:36](https://github.com/lapps/vocabulary-pages/blob/master/templates/discriminator-page.template#L36)

An example of what needs to be done can be found in the [vocab-element.template:9-11](
https://github.com/lapps/vocabulary-pages/blob/master/templates/vocab-element.template#L9-L11)

However, if we want to preserve existing HTML markup then we need to output the line(s) with mkp.yieldUnescaped (mkp is the `writer` object provided by the Groovy builder ... no idea what *mkp* stands for).

Also, the code in the *vocab-element.template* assumes that the text to be converted into a link is wrapped in a &lt;link/> tag.  Currently that is not the case for links in the description text so we would either need to find and modify all the links in descriptions (I think there about seven instances) or find tokens that begin with http and wrap them (minus any trailing punctuation) in anchor tags.

**Comment by marcverhagen** [comment]
I think that gives me enough to at least try. And probably add in all the link tags.

**Comment by marcverhagen** [comment]
So I made those changes and simplified the layout of discriminators.html  a wee little bit. Changes were made to https://github.com/lapps/vocabulary-pages in branch issue55.

If the changes look okay this issue can be closed.

One question, is the syntax to be used for the template files described somewhere?

**Comment by ksuderman** [comment]
Great!

The syntax for the templates is just Groovy, or in particular the syntax for Groovy's builtin [MarkupBuilder](http://docs.groovy-lang.org/latest/html/api/groovy/xml/MarkupBuilder.html) class.
